version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./dumpFile.sql:/docker-entrypoint-initdb.d/dumpFile.sql
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8001:5432"
  app:
    build: ./ws-product-python
    restart: always
    ports:
      - 5000:5000
    environment:
      - SQL_URI=${DATABASE_URL}
    depends_on:
      - db
    
