# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push
  # Triggers the workflow on push or pull request events but only for the main bran
  # Allows you to run this workflow manually from the Actions ta

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Prepare tag
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to DockerHub
        env:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $username -p $password
      - name: docker build
        run: |
          pwd
          
          docker build -f ./mysqlDockerfile -t iverse/postgres:${{ steps.branch_name.outputs.SOURCE_NAME }}.${{ steps.branch_name.outputs.SOURCE_TAG }}.${{ steps.branch_name.outputs.SOURCE_BRANCH }}
      - name: docker build
        run: |
          pwd
          docker build ./ws-product-python -t iverse/api-python:1.0.0
      - name: push
        run: |
          docker push iverse/api-python:1.0.0
      - name: docker compose to k8s
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.24.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv ./kompose /usr/local/bin/kompose
          ls
          kompose convert -f ./docker-compose.yaml
      - name: install minkikue and kubectl 
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          minikube start
      - name: deploy helm with minikbue 
        run : | 
          echo "install terraform"
          git clone https://github.com/hashicorp/terraform.git
          cd terraform
          go install
          echo $PATH
          cd /home/runner/work/Sampleproject/Sampleproject
          ls 
          terraform -help
          terraform -version
          terraform init 
          terraform apply -auto-approve
